name: build

on: [push]

jobs:

  windows-msvc:
    name: ${{ matrix.config }} Windows ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch: [arm64, x86, x64]
#        arch: [x86, x64]
        include:
          - arch: arm64
            platform: ARM64

          - arch: x86
            platform: Win32

          - arch: x64
            platform: x64

    steps:
    - uses: microsoft/setup-msbuild@v1.0.2

    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build
      run: |
        if [ ${{ matrix.arch }} == "arm64" ]; then
          msbuild build-VS2019-arm\pcre.sln /m /p:Configuration=Release,Platform=${{ matrix.platform }}
        else
          msbuild build-VS2019\pcre.sln /m /p:Configuration=Release,Platform=${{ matrix.platform }}
        fi
#      run: msbuild build-VS2019\pcre.sln /m /p:Configuration=Release,Platform=${{ matrix.platform }}
